# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCBB2M7GPUwKVXsdqFaCyh1f_n7G8DNU
"""

import pandas as pd

# Load your files
stock_df = pd.read_csv('/content/reliance_stock_price.csv')
news_df = pd.read_csv('/content/reliance_news_with_sentiment.csv')

# Fix date formats
stock_df['Date'] = pd.to_datetime(stock_df['Date'], format='%d-%m-%Y')
news_df['Date'] = pd.to_datetime(news_df['Date'], format='%d-%b-%y')  # ← fixed format

# Keep only required columns (remove link)
news_df = news_df[['Date', 'news', 'Sentiment Score', 'Sentiment Category']]

# Group news by date (if multiple headlines)
news_df_grouped = news_df.groupby('Date').agg({
    'news': lambda x: ' || '.join(x.dropna().astype(str)),
    'Sentiment Score': lambda x: round(x.mean(), 4),
    'Sentiment Category': lambda x: x.mode()[0] if not x.mode().empty else 'Neutral'
}).reset_index()

# Merge into stock data
merged_df = pd.merge(stock_df, news_df_grouped, on='Date', how='left')

# Fill blanks
merged_df['news'] = merged_df['news'].fillna('')
merged_df['Sentiment Score'] = merged_df['Sentiment Score'].fillna(0)
merged_df['Sentiment Category'] = merged_df['Sentiment Category'].fillna('Neutral')

# Save final file
merged_df.to_excel('/content/reliance_sentiment_cleaned_final.xlsx', index=False)

print(" Success: Final merged Excel is ready!")