# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J973hUWbEBzm00zsJLxrxEKQ4OjSvNK9
"""

import pandas as pd
from textblob import TextBlob

# Load your file
df = pd.read_csv("reliance_news_sentiment.csv")

# Convert 'Date' to datetime
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

# Define sentiment scoring function
def get_sentiment(text):
    blob = TextBlob(str(text))
    polarity = blob.sentiment.polarity
    if polarity > 0.05:
        return polarity, 'Positive'
    elif polarity < -0.05:
        return polarity, 'Negative'
    else:
        return polarity, 'Neutral'

# Apply sentiment to 'Headline' column
df[['Sentiment Score', 'Sentiment Category']] = df['news'].apply(lambda x: pd.Series(get_sentiment(x)))

# Save the final output
df.to_csv("reliance_sentiment_final_2024.csv", index=False)

print(" Final file with sentiment saved as 'reliance_sentiment_final_2024.csv'")

